applicationName: dice
application:
  annotations:
    lab: helm

backend:
  additionalLabels:
    tier: backend
  replicas: 1
  podLabels:
    tier: backend
  image: kahootali/python-backend
  imagePullPolicy: IfNotPresent
  containerPort: 8080
  serviceType: ClusterIP 

frontend:
  additionalLabels:
    tier: frontend
  replicas: 1
  podLabels:
    tier: frontend
  image: kahootali/node-frontend
  imagePullPolicy: IfNotPresent
  containerPort: 8080
  nodePort: 31000
  serviceType: "NodePort"