applicationName: dice
application:
  annotations:
    lab: helm

backend:
  replicas: 1
  image: kahootali/python-backend
  imagePullPolicy: IfNotPresent
  containerPort: 8080
  serviceType: ClusterIP 

frontend:
  replicas: 1
  image: kahootali/node-frontend
  imagePullPolicy: IfNotPresent
  containerPort: 8080
  nodePort: 31000
  serviceType: "NodePort"