applicationName: dice
application:
  annotations:
    lab: helm

backend:
  replicas: 1
  image: kahootali/python-backend:batch8
  imagePullPolicy: IfNotPresent
  containerPort: 8080
  service:
    type: ClusterIP
    port: 8080


frontend:
  replicas: 1
  image: kahootali/node-frontend:batch8
  imagePullPolicy: IfNotPresent
  containerPort: 8080
  env:
  - name: BACKEND_URL
    value: dice-backend:8080 
  service:
    port: 8080
    type: "NodePort"
    nodePort: 31001