applicationName: dev

backend:
  replicas: 1
  image: kahootali/python-backend:batch7
  service:
    type: ClusterIP
    port: 9080

frontend:
  image: kahootali/node-frontend:batch7
  env:
  - name: BACKEND_URL
    value: dev-backend:9080 
  replicas: 1
  service:
    nodePort: 32001