apiVersion: v1
kind: Service
metadata:
  name: {{ template "application.name" . }}-backend
spec:
  type: {{ .Values.backend.service.type }}
  selector:
{{ include "application-backend.labels" . | indent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.containerPort }}