apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: {{ .Values.backend.serviceType }}
  selector:
{{ include "application.labels" . | indent 4 }}
{{- if .Values.backend.additionalLabels }}
{{ toYaml .Values.backend.additionalLabels | indent 4 }}
{{- end }}
  ports:
    - protocol: TCP
      port: {{ .Values.backend.containerPort }}
      targetPort: {{ .Values.backend.containerPort }}