apiVersion: v1
kind: Service
metadata:
  name: {{ template "application.name" . }}-frontend
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
{{ include "application.labels" . | indent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.containerPort }}
      nodePort: {{ .Values.frontend.service.nodePort }}