apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
{{ include "application.labels" . | indent 4 }}
{{- if .Values.application.annotations }}
  annotations:
{{ toYaml .Values.application.annotations | indent 4 }}
{{- end }}
  name: {{ template "application.name" . }}-frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
{{ include "application.labels" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "application.labels" . | indent 8 }}
    spec:      
      containers:
      - name: {{ template "application.name" . }}-frontend
        image: "{{ .Values.frontend.image }}"
{{- if .Values.frontend.env }}
        env:
{{ toYaml .Values.frontend.env | indent 10 }}
        {{- end }}
        imagePullPolicy: {{ .Values.frontend.imagePullPolicy }}   
        ports:
        - containerPort: {{ .Values.frontend.containerPort }}
          name: tcp