apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
{{ include "application.labels" . | indent 4 }}
{{- if .Values.frontend.additionalLabels }}
{{ toYaml .Values.frontend.additionalLabels | indent 4 }}
{{- end }}
{{- if .Values.application.annotations }}
  annotations:
{{ toYaml .Values.application.annotations | indent 4 }}
{{- end }}
  name: {{ template "application.name" . }}-frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
{{- if .Values.frontend.podLabels }}
{{ include "application.labels" . | indent 6 }}
{{ toYaml .Values.frontend.podLabels | indent 6 }}
{{- end }}
  template:
    metadata:
      labels:
{{- if .Values.frontend.podLabels }}
{{ include "application.labels" . | indent 8 }}
{{ toYaml .Values.frontend.podLabels | indent 8 }}
{{- end }}
    spec:      
      containers:
      - name: {{ template "application.name" . }}-frontend
        image: "{{ .Values.frontend.image }}"    
        imagePullPolicy: {{ .Values.frontend.imagePullPolicy }}   
        ports:
        - containerPort: {{ .Values.frontend.containerPort }}
          name: tcp